### ISSUE TITLE
DistributionGoSymbolsExtractor plugin produces invalid data

### ISSUE THREAD

**Issue by nforro** [gofed/infra#30]
*DistributionGoSymbolsExtractor._generateGolangProjectDistributionPackagesArtefact* method returns data that fail to validate against *golang-project-distribution-packages* schema.

Example of exception raised:

           ValidationError: {'name': 'encoding/json', 'location': ['status_verifier.go', 'status_modifier.go']} is not of type u'string'
           
           Failed validating u'type' in schema[u'properties'][u'data'][u'properties'][u'dependencies'][u'items'][u'properties'][u'dependencies'][u'items']:
               {u'description': u'dependency', u'type': u'string'}
           
           On instance[u'data'][u'dependencies'][0][u'dependencies'][0]:
               {'location': ['status_verifier.go', 'status_modifier.go'],
                'name': 'encoding/json'}

**Comment by ingvagabund** [comment]
https://github.com/gofed/infra/commit/c96329ee10b311a721b91597e6bd61ca0d459ad4
